In [5]:
import pandas as pd
df=pd.read_csv('states.csv')
df.head()

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
0,Alabama,14.6%,10.1%,-4.5%,215000,2545000,165534,152206,$310,False,799176.0,910775,111599.0,989855
1,Alaska,19.9%,14.9%,-5%,36000,390000,17995,16205,$750,True,122334.0,166625,44291.0,88966
2,Arizona,16.9%,10.8%,-6.1%,410000,3288000,179445,124346,$230,True,1201770.0,1716198,514428.0,1175624
3,Arkansas,17.5%,9.5%,-8%,234000,1365000,63357,56843,$306,True,556851.0,920194,363343.0,606146
4,California,18.5%,8.6%,-9.9%,3826000,19552000,1415428,1239893,$309,True,7755381.0,11843081,4087700.0,5829777

In [7]:
import pandas as pd
df=pd.read_csv('states.csv')
df.head(10)

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
0,Alabama,14.6%,10.1%,-4.5%,215000,2545000,165534,152206,$310,False,799176.0,910775,111599.0,989855
1,Alaska,19.9%,14.9%,-5%,36000,390000,17995,16205,$750,True,122334.0,166625,44291.0,88966
2,Arizona,16.9%,10.8%,-6.1%,410000,3288000,179445,124346,$230,True,1201770.0,1716198,514428.0,1175624
3,Arkansas,17.5%,9.5%,-8%,234000,1365000,63357,56843,$306,True,556851.0,920194,363343.0,606146
4,California,18.5%,8.6%,-9.9%,3826000,19552000,1415428,1239893,$309,True,7755381.0,11843081,4087700.0,5829777
5,Colorado,15.9%,8.1%,-7.8%,419000,2949000,108311,67062,$318,True,783420.0,1375264,591844.0,820234
6,Connecticut,9.1%,6%,-3.1%,110000,2148000,102917,80759,$357,True,NaN,761137,NaN,644136
7,Delaware,9.7%,5.9%,-3.8%,35000,564000,25379,21467,$330,True,223324.0,236702,13378.0,186835
8,District of Columbia,7.6%,3.8%,-3.8%,25000,388000,17666,1224,$183,True,235786.0,255491,19705.0,90492
9,Florida,21.3%,13.3%,-8%,1597000,8847000,1531714,1428712,$305,False,3104996.0,3644673,539677.0,4149593

In [8]:
import pandas as pd
df=pd.read_csv('states.csv')
df.tail()

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
47,Washington,14.2%,6.6%,-7.6%,537000,3986000,158245,110476,$238,True,1117576.0,1788536,670960.0,1238649
48,West Virginia,14.6%,6%,-8.6%,156000,976000,33235,29163,$388,True,354544.0,575645,221101.0,423500
49,Wisconsin,9.4%,5.7%,-3.7%,211000,3521000,224208,190542,$332,False,985531.0,1046897,61366.0,1084854
50,Wyoming,14.9%,11.5%,-3.4%,20000,335000,22076,20313,$459,False,67518.0,63583,-3935.0,99128
51,United States,15.5%,9.4%,6.1%,19304000,172292000,11081330,9389609,$291,NaN,56392477.0,73532931,16106157.0,57149984

In [35]:
import pandas as pd
df=pd.read_csv('states.csv')
df.tail(45)

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
7,Delaware,9.7%,5.9%,-3.8%,35000,564000,25379,21467,$330,True,223324.0,236702,13378.0,186835
8,District of Columbia,7.6%,3.8%,-3.8%,25000,388000,17666,1224,$183,True,235786.0,255491,19705.0,90492
9,Florida,21.3%,13.3%,-8%,1597000,8847000,1531714,1428712,$305,False,3104996.0,3644673,539677.0,4149593
10,Georgia,19.7%,13.9%,-5.8%,581000,5240000,478016,427353,$291,False,1535090.0,1782301,247211.0,1574058
11,Hawaii,7.9%,4%,-3.9%,54000,867000,13313,10958,$270,True,288357.0,341200,52843.0,252514
12,Idaho,17.7%,11%,-6.7%,109000,836000,94270,82802,$265,False,238150.0,293905,55755.0,294284
13,Illinois,13.8%,7.1%,-6.7%,850000,7359000,335243,259701,$237,True,2626943.0,3117939,490996.0,2118300
14,Indiana,14.8%,9.6%,-5.2%,339000,3825000,168884,139437,$259,True,1120674.0,1489805,369131.0,1181014
15,Iowa,9.3%,5%,-4.3%,132000,1862000,48949,42595,$307,True,493515.0,619055,125540.0,587780
16,Kansas,13.9%,9.1%,-4.8%,137000,1659000,89566,75815,$247,False,378160.0,421638,43478.0,499753
17,Kentucky,15.3%,6%,-9.3%,404000,2316000,74640,56488,$258,True,606805.0,1220788,613983.0,881938
18,Louisiana,17.8%,11.9%,-5.9%,269000,2295000,184403,170806,$362,True,1019787.0,1328708,308921.0,817272
19,Maine,10.1%,8.4%,-1.7%,22000,702000,75240,63896,$342,False,NaN,273160,NaN,315160
20,Maryland,11.3%,6.6%,-4.7%,278000,3700000,135208,100844,$243,True,856297.0,1252304,396007.0,960848
21,Massachusetts,4.4%,2.8%,-1.6%,107000,4232000,207121,157751,$190,True,1296359.0,1684328,387969.0,1252277
22,Michigan,12.4%,6.1%,-6.3%,618000,5876000,313123,275080,$233,True,1912009.0,2300958,388949.0,1947787
23,Minnesota,9.1%,4.5%,-4.6%,250000,3319000,74060,47266,$203,True,873040.0,1051509,178469.0,944222
24,Mississippi,18.2%,12.7%,-5.5%,161000,1326000,77747,73246,$306,False,637229.0,693869,56640.0,571699
25,Missouri,13.2%,9.8%,-3.4%,203000,3389000,252044,225878,$315,False,846084.0,967284,121200.0,1163543
26,Montana,17.3%,11.6%,-5.7%,58000,510000,51758,44091,$306,True,148974.0,224048,75074.0,209389
27,Nebraska,11.5%,8.2%,-3.3%,62000,1100000,80213,72091,$296,False,244600.0,242702,-1898.0,322796
28,Nevada,22.6%,12.3%,-10.3%,294000,1505000,79876,71472,$268,True,332560.0,614298,281738.0,471747
29,New Hampshire,11.1%,6.3%,-4.8%,63000,853000,49114,31151,$261,True,127082.0,189429,62347.0,275803
30,New Jersey,13.2%,8.7%,-4.5%,398000,5450000,249395,205242,$322,True,1283851.0,1784529,500678.0,1528961
31,New Mexico,19.6%,10.9%,-8.7%,178000,884000,47497,32703,$212,True,457678.0,766732,309054.0,385918
32,New York,11.9%,7.1%,-4.8%,939000,10895000,224014,123830,$178,True,5678417.0,6431165,752748.0,3424666
33,North Carolina,16.8%,11.2%,-5.6%,552000,4934000,545354,499178,$401,False,1595952.0,2072282,476330.0,1823454
34,North Dakota,9.8%,7.8%,-2%,15000,450000,20536,17630,$262,True,69980.0,89763,19783.0,122294
35,Ohio,12.3%,6.5%,-5.8%,664000,6831000,212046,174448,$250,True,2341481.0,3003170,661689.0,2208504
36,Oklahoma,18.9%,13.9%,-5%,192000,1948000,130178,113209,$298,False,790051.0,788544,-1507.0,693677
37,Oregon,17.1%,7%,-10.1%,403000,2070000,131167,95507,$253,True,626356.0,1021862,395506.0,784032
38,Pennsylvania,10.2%,6.4%,-3.8%,479000,7502000,412347,321345,$248,True,2386046.0,2883114,497068.0,2588577
39,Rhode Island,12.2%,5.7%,-6.5%,68000,597000,35583,30015,$250,True,190833.0,287173,96340.0,208324
40,South Carolina,17.5%,10.9%,-6.6%,317000,2487000,204846,186345,$312,False,889744.0,994804,105060.0,974114
41,South Dakota,12.4%,10.2%,-2.2%,19000,449000,24578,22005,$307,False,115501.0,119835,4334.0,161464
42,Tennessee,14.4%,10.3%,-4.1%,266000,3369000,231705,203112,$299,False,1244516.0,1627100,382584.0,1266920
43,Texas,23.7%,17.1%,-6.6%,1781000,13709000,1092650,913177,$271,False,4441605.0,4770229,328624.0,3765946
44,Utah,15.3%,10.5%,-4.8%,143000,1897000,164415,145288,$187,False,294029.0,314182,20153.0,358887
45,Vermont,8%,3.8%,-4.2%,26000,345000,27883,19575,$300,True,161081.0,175597,14516.0,136021
46,Virginia,13.1%,9.1%,-4%,327000,4850000,378838,319068,$276,False,935434.0,988821,53387.0,1392261
47,Washington,14.2%,6.6%,-7.6%,537000,3986000,158245,110476,$238,True,1117576.0,1788536,670960.0,1238649
48,West Virginia,14.6%,6%,-8.6%,156000,976000,33235,29163,$388,True,354544.0,575645,221101.0,423500
49,Wisconsin,9.4%,5.7%,-3.7%,211000,3521000,224208,190542,$332,False,985531.0,1046897,61366.0,1084854
50,Wyoming,14.9%,11.5%,-3.4%,20000,335000,22076,20313,$459,False,67518.0,63583,-3935.0,99128
51,United States,15.5%,9.4%,6.1%,19304000,172292000,11081330,9389609,$291,NaN,56392477.0,73532931,16106157.0,57149984

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   State                                         52 non-null     object
 1   Uninsured Rate (2010)                         52 non-null     object
 2   Uninsured Rate (2015)                         52 non-null     object
 3   Uninsured Rate Change (2010-2015)             52 non-null     object
 4   Health Insurance Coverage Change (2010-2015)  52 non-null     int64
 5   Employer Health Insurance Coverage (2015)     52 non-null     int64
 6   Marketplace Health Insurance Coverage (2016)  52 non-null     int64
 7   Marketplace Tax Credits (2016)                52 non-null     int64
 8   Average Monthly Tax Credit (2016)             52 non-null     object
 9   State Medicaid Expansion (2016)               51 non-null     object
 10  Medicaid Enrollment (2013)                    50 non-null     float64
 11  Medicaid Enrollment (2016)                    52 non-null     int64
 12  Medicaid Enrollment Change (2013-2016)        50 non-null     float64
 13  Medicare Enrollment (2016)                    52 non-null     int64
dtypes: float64(2), int64(6), object(6)
memory usage: 5.8+ KB

In [11]:
df.describe()

,Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
count,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.000000e+01,5.200000e+01,5.000000e+01,5.200000e+01
mean,7.479423e+05,6.626615e+06,4.262050e+05,3.611388e+05,2.255699e+06,2.828190e+06,6.442463e+05,2.173923e+06
std,2.691466e+06,2.370240e+07,1.538234e+06,1.306590e+06,7.945644e+06,1.017933e+07,2.306655e+06,7.855834e+06
min,1.500000e+04,3.350000e+05,1.331300e+04,1.224000e+03,6.751800e+04,6.358300e+04,-3.935000e+03,8.896600e+04
25%,9.725000e+04,8.797500e+05,5.109700e+04,4.371700e+04,2.897750e+05,3.091128e+05,5.397900e+04,3.208870e+05
50%,2.245000e+05,2.305500e+06,1.306725e+05,9.817550e+04,7.946135e+05,9.780525e+05,2.341560e+05,8.187530e+05
75%,4.122500e+05,4.386500e+06,2.260822e+05,1.936845e+05,1.274017e+06,1.732724e+06,4.562492e+05,1.298255e+06
max,1.930400e+07,1.722920e+08,1.108133e+07,9.389609e+06,5.639248e+07,7.353293e+07,1.610616e+07,5.714998e+07

In [14]:
df.shape

(52, 14)

In [16]:
df.columns

Index(['State', 'Uninsured Rate (2010)', 'Uninsured Rate (2015)',
       'Uninsured Rate Change (2010-2015)',
       'Health Insurance Coverage Change (2010-2015)',
       'Employer Health Insurance Coverage (2015)',
       'Marketplace Health Insurance Coverage (2016)',
       'Marketplace Tax Credits (2016)', 'Average Monthly Tax Credit (2016)',
       'State Medicaid Expansion (2016)', 'Medicaid Enrollment (2013)',
       'Medicaid Enrollment (2016)', 'Medicaid Enrollment Change (2013-2016)',
       'Medicare Enrollment (2016)'],
      dtype='object')

In [17]:
df.index

RangeIndex(start=0, stop=52, step=1)

In [18]:
df.dtypes

State                                            object
Uninsured Rate (2010)                            object
Uninsured Rate (2015)                            object
Uninsured Rate Change (2010-2015)                object
Health Insurance Coverage Change (2010-2015)      int64
Employer Health Insurance Coverage (2015)         int64
Marketplace Health Insurance Coverage (2016)      int64
Marketplace Tax Credits (2016)                    int64
Average Monthly Tax Credit (2016)                object
State Medicaid Expansion (2016)                  object
Medicaid Enrollment (2013)                      float64
Medicaid Enrollment (2016)                        int64
Medicaid Enrollment Change (2013-2016)          float64
Medicare Enrollment (2016)                        int64
dtype: object

In [27]:
print(df.columns)

Index(['State', 'Uninsured Rate (2010)', 'Uninsured Rate (2015)',
       'Uninsured Rate Change (2010-2015)',
       'Health Insurance Coverage Change (2010-2015)',
       'Employer Health Insurance Coverage (2015)',
       'Marketplace Health Insurance Coverage (2016)',
       'Marketplace Tax Credits (2016)', 'Average Monthly Tax Credit (2016)',
       'State Medicaid Expansion (2016)', 'Medicaid Enrollment (2013)',
       'Medicaid Enrollment (2016)', 'Medicaid Enrollment Change (2013-2016)',
       'Medicare Enrollment (2016)'],
      dtype='object')

In [30]:
df.columns = df.columns.str.strip()  # Removes extra spaces

In [33]:
df['Health Insurance Coverage Change (2010-2015)']

0       215000
1        36000
2       410000
3       234000
4      3826000
5       419000
6       110000
7        35000
8        25000
9      1597000
10      581000
11       54000
12      109000
13      850000
14      339000
15      132000
16      137000
17      404000
18      269000
19       22000
20      278000
21      107000
22      618000
23      250000
24      161000
25      203000
26       58000
27       62000
28      294000
29       63000
30      398000
31      178000
32      939000
33      552000
34       15000
35      664000
36      192000
37      403000
38      479000
39       68000
40      317000
41       19000
42      266000
43     1781000
44      143000
45       26000
46      327000
47      537000
48      156000
49      211000
50       20000
51    19304000
Name: Health Insurance Coverage Change (2010-2015), dtype: int64

In [36]:
df[['State','Uninsured Rate (2015)']]

                   State Uninsured Rate (2015)
0               Alabama                  10.1%
1                Alaska                  14.9%
2               Arizona                  10.8%
3              Arkansas                   9.5%
4             California                  8.6%
5               Colorado                  8.1%
6            Connecticut                    6%
7              Delaware                   5.9%
8   District of Columbia                  3.8%
9               Florida                  13.3%
10              Georgia                  13.9%
11                Hawaii                    4%
12                 Idaho                   11%
13             Illinois                   7.1%
14              Indiana                   9.6%
15                 Iowa                     5%
16               Kansas                   9.1%
17              Kentucky                    6%
18            Louisiana                  11.9%
19                Maine                   8.4%
20              Maryland                  6.6%
21         Massachusetts                  2.8%
22             Michigan                   6.1%
23             Minnesota                  4.5%
24          Mississippi                  12.7%
25             Missouri                   9.8%
26              Montana                  11.6%
27             Nebraska                   8.2%
28                Nevada                 12.3%
29        New Hampshire                   6.3%
30           New Jersey                   8.7%
31            New Mexico                 10.9%
32              New York                  7.1%
33       North Carolina                  11.2%
34         North Dakota                   7.8%
35                 Ohio                   6.5%
36             Oklahoma                  13.9%
37                Oregon                    7%
38         Pennsylvania                   6.4%
39          Rhode Island                  5.7%
40       South Carolina                  10.9%
41         South Dakota                  10.2%
42            Tennessee                  10.3%
43                Texas                  17.1%
44                 Utah                  10.5%
45               Vermont                  3.8%
46             Virginia                   9.1%
47            Washington                  6.6%
48        West Virginia                     6%
49            Wisconsin                   5.7%
50               Wyoming                 11.5%
51         United States                  9.4%

In [42]:
df.loc[[8,9]]

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
8,District of Columbia,7.6%,3.8%,-3.8%,25000,388000,17666,1224,$183,True,235786.0,255491,19705.0,90492
9,Florida,21.3%,13.3%,-8%,1597000,8847000,1531714,1428712,$305,False,3104996.0,3644673,539677.0,4149593

In [44]:
df[df['Employer Health Insurance Coverage (2015)']>10]

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
0,Alabama,14.6%,10.1%,-4.5%,215000,2545000,165534,152206,$310,False,799176.0,910775,111599.0,989855
1,Alaska,19.9%,14.9%,-5%,36000,390000,17995,16205,$750,True,122334.0,166625,44291.0,88966
2,Arizona,16.9%,10.8%,-6.1%,410000,3288000,179445,124346,$230,True,1201770.0,1716198,514428.0,1175624
3,Arkansas,17.5%,9.5%,-8%,234000,1365000,63357,56843,$306,True,556851.0,920194,363343.0,606146
4,California,18.5%,8.6%,-9.9%,3826000,19552000,1415428,1239893,$309,True,7755381.0,11843081,4087700.0,5829777
5,Colorado,15.9%,8.1%,-7.8%,419000,2949000,108311,67062,$318,True,783420.0,1375264,591844.0,820234
6,Connecticut,9.1%,6%,-3.1%,110000,2148000,102917,80759,$357,True,NaN,761137,NaN,644136
7,Delaware,9.7%,5.9%,-3.8%,35000,564000,25379,21467,$330,True,223324.0,236702,13378.0,186835
8,District of Columbia,7.6%,3.8%,-3.8%,25000,388000,17666,1224,$183,True,235786.0,255491,19705.0,90492
9,Florida,21.3%,13.3%,-8%,1597000,8847000,1531714,1428712,$305,False,3104996.0,3644673,539677.0,4149593
10,Georgia,19.7%,13.9%,-5.8%,581000,5240000,478016,427353,$291,False,1535090.0,1782301,247211.0,1574058
11,Hawaii,7.9%,4%,-3.9%,54000,867000,13313,10958,$270,True,288357.0,341200,52843.0,252514
12,Idaho,17.7%,11%,-6.7%,109000,836000,94270,82802,$265,False,238150.0,293905,55755.0,294284
13,Illinois,13.8%,7.1%,-6.7%,850000,7359000,335243,259701,$237,True,2626943.0,3117939,490996.0,2118300
14,Indiana,14.8%,9.6%,-5.2%,339000,3825000,168884,139437,$259,True,1120674.0,1489805,369131.0,1181014
15,Iowa,9.3%,5%,-4.3%,132000,1862000,48949,42595,$307,True,493515.0,619055,125540.0,587780
16,Kansas,13.9%,9.1%,-4.8%,137000,1659000,89566,75815,$247,False,378160.0,421638,43478.0,499753
17,Kentucky,15.3%,6%,-9.3%,404000,2316000,74640,56488,$258,True,606805.0,1220788,613983.0,881938
18,Louisiana,17.8%,11.9%,-5.9%,269000,2295000,184403,170806,$362,True,1019787.0,1328708,308921.0,817272
19,Maine,10.1%,8.4%,-1.7%,22000,702000,75240,63896,$342,False,NaN,273160,NaN,315160
20,Maryland,11.3%,6.6%,-4.7%,278000,3700000,135208,100844,$243,True,856297.0,1252304,396007.0,960848
21,Massachusetts,4.4%,2.8%,-1.6%,107000,4232000,207121,157751,$190,True,1296359.0,1684328,387969.0,1252277
22,Michigan,12.4%,6.1%,-6.3%,618000,5876000,313123,275080,$233,True,1912009.0,2300958,388949.0,1947787
23,Minnesota,9.1%,4.5%,-4.6%,250000,3319000,74060,47266,$203,True,873040.0,1051509,178469.0,944222
24,Mississippi,18.2%,12.7%,-5.5%,161000,1326000,77747,73246,$306,False,637229.0,693869,56640.0,571699
25,Missouri,13.2%,9.8%,-3.4%,203000,3389000,252044,225878,$315,False,846084.0,967284,121200.0,1163543
26,Montana,17.3%,11.6%,-5.7%,58000,510000,51758,44091,$306,True,148974.0,224048,75074.0,209389
27,Nebraska,11.5%,8.2%,-3.3%,62000,1100000,80213,72091,$296,False,244600.0,242702,-1898.0,322796
28,Nevada,22.6%,12.3%,-10.3%,294000,1505000,79876,71472,$268,True,332560.0,614298,281738.0,471747
29,New Hampshire,11.1%,6.3%,-4.8%,63000,853000,49114,31151,$261,True,127082.0,189429,62347.0,275803
30,New Jersey,13.2%,8.7%,-4.5%,398000,5450000,249395,205242,$322,True,1283851.0,1784529,500678.0,1528961
31,New Mexico,19.6%,10.9%,-8.7%,178000,884000,47497,32703,$212,True,457678.0,766732,309054.0,385918
32,New York,11.9%,7.1%,-4.8%,939000,10895000,224014,123830,$178,True,5678417.0,6431165,752748.0,3424666
33,North Carolina,16.8%,11.2%,-5.6%,552000,4934000,545354,499178,$401,False,1595952.0,2072282,476330.0,1823454
34,North Dakota,9.8%,7.8%,-2%,15000,450000,20536,17630,$262,True,69980.0,89763,19783.0,122294
35,Ohio,12.3%,6.5%,-5.8%,664000,6831000,212046,174448,$250,True,2341481.0,3003170,661689.0,2208504
36,Oklahoma,18.9%,13.9%,-5%,192000,1948000,130178,113209,$298,False,790051.0,788544,-1507.0,693677
37,Oregon,17.1%,7%,-10.1%,403000,2070000,131167,95507,$253,True,626356.0,1021862,395506.0,784032
38,Pennsylvania,10.2%,6.4%,-3.8%,479000,7502000,412347,321345,$248,True,2386046.0,2883114,497068.0,2588577
39,Rhode Island,12.2%,5.7%,-6.5%,68000,597000,35583,30015,$250,True,190833.0,287173,96340.0,208324
40,South Carolina,17.5%,10.9%,-6.6%,317000,2487000,204846,186345,$312,False,889744.0,994804,105060.0,974114
41,South Dakota,12.4%,10.2%,-2.2%,19000,449000,24578,22005,$307,False,115501.0,119835,4334.0,161464
42,Tennessee,14.4%,10.3%,-4.1%,266000,3369000,231705,203112,$299,False,1244516.0,1627100,382584.0,1266920
43,Texas,23.7%,17.1%,-6.6%,1781000,13709000,1092650,913177,$271,False,4441605.0,4770229,328624.0,3765946
44,Utah,15.3%,10.5%,-4.8%,143000,1897000,164415,145288,$187,False,294029.0,314182,20153.0,358887
45,Vermont,8%,3.8%,-4.2%,26000,345000,27883,19575,$300,True,161081.0,175597,14516.0,136021
46,Virginia,13.1%,9.1%,-4%,327000,4850000,378838,319068,$276,False,935434.0,988821,53387.0,1392261
47,Washington,14.2%,6.6%,-7.6%,537000,3986000,158245,110476,$238,True,1117576.0,1788536,670960.0,1238649
48,West Virginia,14.6%,6%,-8.6%,156000,976000,33235,29163,$388,True,354544.0,575645,221101.0,423500
49,Wisconsin,9.4%,5.7%,-3.7%,211000,3521000,224208,190542,$332,False,985531.0,1046897,61366.0,1084854
50,Wyoming,14.9%,11.5%,-3.4%,20000,335000,22076,20313,$459,False,67518.0,63583,-3935.0,99128
51,United States,15.5%,9.4%,6.1%,19304000,172292000,11081330,9389609,$291,NaN,56392477.0,73532931,16106157.0,57149984

In [45]:
df.iloc[3]

State                                           Arkansas
Uninsured Rate (2010)                               17.5%
Uninsured Rate (2015)                                9.5%
Uninsured Rate Change (2010-2015)                    -8%
Health Insurance Coverage Change (2010-2015)       234000
Employer Health Insurance Coverage (2015)         1365000
Marketplace Health Insurance Coverage (2016)        63357
Marketplace Tax Credits (2016)                      56843
Average Monthly Tax Credit (2016)                   $306
State Medicaid Expansion (2016)                      True
Medicaid Enrollment (2013)                       556851.0
Medicaid Enrollment (2016)                         920194
Medicaid Enrollment Change (2013-2016)           363343.0
Medicare Enrollment (2016)                         606146
Name: 3, dtype: object

In [47]:
df=pd.DataFrame(data,index=['day1'])

NameError: name 'data' is not defined

In [48]:
df.shape

(52, 14)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   State                                         52 non-null     object
 1   Uninsured Rate (2010)                         52 non-null     object
 2   Uninsured Rate (2015)                         52 non-null     object
 3   Uninsured Rate Change (2010-2015)             52 non-null     object
 4   Health Insurance Coverage Change (2010-2015)  52 non-null     int64
 5   Employer Health Insurance Coverage (2015)     52 non-null     int64
 6   Marketplace Health Insurance Coverage (2016)  52 non-null     int64
 7   Marketplace Tax Credits (2016)                52 non-null     int64
 8   Average Monthly Tax Credit (2016)             52 non-null     object
 9   State Medicaid Expansion (2016)               51 non-null     object
 10  Medicaid Enrollment (2013)                    50 non-null     float64
 11  Medicaid Enrollment (2016)                    52 non-null     int64
 12  Medicaid Enrollment Change (2013-2016)        50 non-null     float64
 13  Medicare Enrollment (2016)                    52 non-null     int64
dtypes: float64(2), int64(6), object(6)
memory usage: 5.8+ KB

In [51]:
df.dtypes

State                                            object
Uninsured Rate (2010)                            object
Uninsured Rate (2015)                            object
Uninsured Rate Change (2010-2015)                object
Health Insurance Coverage Change (2010-2015)      int64
Employer Health Insurance Coverage (2015)         int64
Marketplace Health Insurance Coverage (2016)      int64
Marketplace Tax Credits (2016)                    int64
Average Monthly Tax Credit (2016)                object
State Medicaid Expansion (2016)                  object
Medicaid Enrollment (2013)                      float64
Medicaid Enrollment (2016)                        int64
Medicaid Enrollment Change (2013-2016)          float64
Medicare Enrollment (2016)                        int64
dtype: object

In [53]:
df.describe()

,Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
count,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.000000e+01,5.200000e+01,5.000000e+01,5.200000e+01
mean,7.479423e+05,6.626615e+06,4.262050e+05,3.611388e+05,2.255699e+06,2.828190e+06,6.442463e+05,2.173923e+06
std,2.691466e+06,2.370240e+07,1.538234e+06,1.306590e+06,7.945644e+06,1.017933e+07,2.306655e+06,7.855834e+06
min,1.500000e+04,3.350000e+05,1.331300e+04,1.224000e+03,6.751800e+04,6.358300e+04,-3.935000e+03,8.896600e+04
25%,9.725000e+04,8.797500e+05,5.109700e+04,4.371700e+04,2.897750e+05,3.091128e+05,5.397900e+04,3.208870e+05
50%,2.245000e+05,2.305500e+06,1.306725e+05,9.817550e+04,7.946135e+05,9.780525e+05,2.341560e+05,8.187530e+05
75%,4.122500e+05,4.386500e+06,2.260822e+05,1.936845e+05,1.274017e+06,1.732724e+06,4.562492e+05,1.298255e+06
max,1.930400e+07,1.722920e+08,1.108133e+07,9.389609e+06,5.639248e+07,7.353293e+07,1.610616e+07,5.714998e+07

In [55]:
import math
print(math.sqrt(8))

2.8284271247461903

In [58]:
import random
random.seed(10)
print(random.random())

0.5714025946899135

In [66]:
import random
print(random.random())

0.5206693596399246

In [71]:
import random
mylist=['apple','orange','kiwi']
print(random.sample(mylist,k=2))

['apple', 'orange']

In [72]:
import random
mylist=['apple','orange','kiwi']
print(random.sample(mylist,k=3))

['apple', 'orange', 'kiwi']

In [78]:
import pandas as pd
df=pd.read_csv('states.csv')

In [79]:
df.tail()

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
47,Washington,14.2%,6.6%,-7.6%,537000,3986000,158245,110476,$238,True,1117576.0,1788536,670960.0,1238649
48,West Virginia,14.6%,6%,-8.6%,156000,976000,33235,29163,$388,True,354544.0,575645,221101.0,423500
49,Wisconsin,9.4%,5.7%,-3.7%,211000,3521000,224208,190542,$332,False,985531.0,1046897,61366.0,1084854
50,Wyoming,14.9%,11.5%,-3.4%,20000,335000,22076,20313,$459,False,67518.0,63583,-3935.0,99128
51,United States,15.5%,9.4%,6.1%,19304000,172292000,11081330,9389609,$291,NaN,56392477.0,73532931,16106157.0,57149984

In [80]:
df.columns

Index(['State', 'Uninsured Rate (2010)', 'Uninsured Rate (2015)',
       'Uninsured Rate Change (2010-2015)',
       'Health Insurance Coverage Change (2010-2015)',
       'Employer Health Insurance Coverage (2015)',
       'Marketplace Health Insurance Coverage (2016)',
       'Marketplace Tax Credits (2016)', 'Average Monthly Tax Credit (2016)',
       'State Medicaid Expansion (2016)', 'Medicaid Enrollment (2013)',
       'Medicaid Enrollment (2016)', 'Medicaid Enrollment Change (2013-2016)',
       'Medicare Enrollment (2016)'],
      dtype='object')

In [82]:
df['Uninsured Rate (2010)']

0     14.6%
1     19.9%
2     16.9%
3     17.5%
4     18.5%
5     15.9%
6      9.1%
7      9.7%
8      7.6%
9     21.3%
10    19.7%
11     7.9%
12    17.7%
13    13.8%
14    14.8%
15     9.3%
16    13.9%
17    15.3%
18    17.8%
19    10.1%
20    11.3%
21     4.4%
22    12.4%
23     9.1%
24    18.2%
25    13.2%
26    17.3%
27    11.5%
28    22.6%
29    11.1%
30    13.2%
31    19.6%
32    11.9%
33    16.8%
34     9.8%
35    12.3%
36    18.9%
37    17.1%
38    10.2%
39    12.2%
40    17.5%
41    12.4%
42    14.4%
43    23.7%
44    15.3%
45       8%
46    13.1%
47    14.2%
48    14.6%
49     9.4%
50    14.9%
51    15.5%
Name: Uninsured Rate (2010), dtype: object

In [85]:

df[df['Employer Health Insurance Coverage (2015)']>10]

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
0,Alabama,14.6%,10.1%,-4.5%,215000,2545000,165534,152206,$310,False,799176.0,910775,111599.0,989855
1,Alaska,19.9%,14.9%,-5%,36000,390000,17995,16205,$750,True,122334.0,166625,44291.0,88966
2,Arizona,16.9%,10.8%,-6.1%,410000,3288000,179445,124346,$230,True,1201770.0,1716198,514428.0,1175624
3,Arkansas,17.5%,9.5%,-8%,234000,1365000,63357,56843,$306,True,556851.0,920194,363343.0,606146
4,California,18.5%,8.6%,-9.9%,3826000,19552000,1415428,1239893,$309,True,7755381.0,11843081,4087700.0,5829777
5,Colorado,15.9%,8.1%,-7.8%,419000,2949000,108311,67062,$318,True,783420.0,1375264,591844.0,820234
6,Connecticut,9.1%,6%,-3.1%,110000,2148000,102917,80759,$357,True,NaN,761137,NaN,644136
7,Delaware,9.7%,5.9%,-3.8%,35000,564000,25379,21467,$330,True,223324.0,236702,13378.0,186835
8,District of Columbia,7.6%,3.8%,-3.8%,25000,388000,17666,1224,$183,True,235786.0,255491,19705.0,90492
9,Florida,21.3%,13.3%,-8%,1597000,8847000,1531714,1428712,$305,False,3104996.0,3644673,539677.0,4149593
10,Georgia,19.7%,13.9%,-5.8%,581000,5240000,478016,427353,$291,False,1535090.0,1782301,247211.0,1574058
11,Hawaii,7.9%,4%,-3.9%,54000,867000,13313,10958,$270,True,288357.0,341200,52843.0,252514
12,Idaho,17.7%,11%,-6.7%,109000,836000,94270,82802,$265,False,238150.0,293905,55755.0,294284
13,Illinois,13.8%,7.1%,-6.7%,850000,7359000,335243,259701,$237,True,2626943.0,3117939,490996.0,2118300
14,Indiana,14.8%,9.6%,-5.2%,339000,3825000,168884,139437,$259,True,1120674.0,1489805,369131.0,1181014
15,Iowa,9.3%,5%,-4.3%,132000,1862000,48949,42595,$307,True,493515.0,619055,125540.0,587780
16,Kansas,13.9%,9.1%,-4.8%,137000,1659000,89566,75815,$247,False,378160.0,421638,43478.0,499753
17,Kentucky,15.3%,6%,-9.3%,404000,2316000,74640,56488,$258,True,606805.0,1220788,613983.0,881938
18,Louisiana,17.8%,11.9%,-5.9%,269000,2295000,184403,170806,$362,True,1019787.0,1328708,308921.0,817272
19,Maine,10.1%,8.4%,-1.7%,22000,702000,75240,63896,$342,False,NaN,273160,NaN,315160
20,Maryland,11.3%,6.6%,-4.7%,278000,3700000,135208,100844,$243,True,856297.0,1252304,396007.0,960848
21,Massachusetts,4.4%,2.8%,-1.6%,107000,4232000,207121,157751,$190,True,1296359.0,1684328,387969.0,1252277
22,Michigan,12.4%,6.1%,-6.3%,618000,5876000,313123,275080,$233,True,1912009.0,2300958,388949.0,1947787
23,Minnesota,9.1%,4.5%,-4.6%,250000,3319000,74060,47266,$203,True,873040.0,1051509,178469.0,944222
24,Mississippi,18.2%,12.7%,-5.5%,161000,1326000,77747,73246,$306,False,637229.0,693869,56640.0,571699
25,Missouri,13.2%,9.8%,-3.4%,203000,3389000,252044,225878,$315,False,846084.0,967284,121200.0,1163543
26,Montana,17.3%,11.6%,-5.7%,58000,510000,51758,44091,$306,True,148974.0,224048,75074.0,209389
27,Nebraska,11.5%,8.2%,-3.3%,62000,1100000,80213,72091,$296,False,244600.0,242702,-1898.0,322796
28,Nevada,22.6%,12.3%,-10.3%,294000,1505000,79876,71472,$268,True,332560.0,614298,281738.0,471747
29,New Hampshire,11.1%,6.3%,-4.8%,63000,853000,49114,31151,$261,True,127082.0,189429,62347.0,275803
30,New Jersey,13.2%,8.7%,-4.5%,398000,5450000,249395,205242,$322,True,1283851.0,1784529,500678.0,1528961
31,New Mexico,19.6%,10.9%,-8.7%,178000,884000,47497,32703,$212,True,457678.0,766732,309054.0,385918
32,New York,11.9%,7.1%,-4.8%,939000,10895000,224014,123830,$178,True,5678417.0,6431165,752748.0,3424666
33,North Carolina,16.8%,11.2%,-5.6%,552000,4934000,545354,499178,$401,False,1595952.0,2072282,476330.0,1823454
34,North Dakota,9.8%,7.8%,-2%,15000,450000,20536,17630,$262,True,69980.0,89763,19783.0,122294
35,Ohio,12.3%,6.5%,-5.8%,664000,6831000,212046,174448,$250,True,2341481.0,3003170,661689.0,2208504
36,Oklahoma,18.9%,13.9%,-5%,192000,1948000,130178,113209,$298,False,790051.0,788544,-1507.0,693677
37,Oregon,17.1%,7%,-10.1%,403000,2070000,131167,95507,$253,True,626356.0,1021862,395506.0,784032
38,Pennsylvania,10.2%,6.4%,-3.8%,479000,7502000,412347,321345,$248,True,2386046.0,2883114,497068.0,2588577
39,Rhode Island,12.2%,5.7%,-6.5%,68000,597000,35583,30015,$250,True,190833.0,287173,96340.0,208324
40,South Carolina,17.5%,10.9%,-6.6%,317000,2487000,204846,186345,$312,False,889744.0,994804,105060.0,974114
41,South Dakota,12.4%,10.2%,-2.2%,19000,449000,24578,22005,$307,False,115501.0,119835,4334.0,161464
42,Tennessee,14.4%,10.3%,-4.1%,266000,3369000,231705,203112,$299,False,1244516.0,1627100,382584.0,1266920
43,Texas,23.7%,17.1%,-6.6%,1781000,13709000,1092650,913177,$271,False,4441605.0,4770229,328624.0,3765946
44,Utah,15.3%,10.5%,-4.8%,143000,1897000,164415,145288,$187,False,294029.0,314182,20153.0,358887
45,Vermont,8%,3.8%,-4.2%,26000,345000,27883,19575,$300,True,161081.0,175597,14516.0,136021
46,Virginia,13.1%,9.1%,-4%,327000,4850000,378838,319068,$276,False,935434.0,988821,53387.0,1392261
47,Washington,14.2%,6.6%,-7.6%,537000,3986000,158245,110476,$238,True,1117576.0,1788536,670960.0,1238649
48,West Virginia,14.6%,6%,-8.6%,156000,976000,33235,29163,$388,True,354544.0,575645,221101.0,423500
49,Wisconsin,9.4%,5.7%,-3.7%,211000,3521000,224208,190542,$332,False,985531.0,1046897,61366.0,1084854
50,Wyoming,14.9%,11.5%,-3.4%,20000,335000,22076,20313,$459,False,67518.0,63583,-3935.0,99128
51,United States,15.5%,9.4%,6.1%,19304000,172292000,11081330,9389609,$291,NaN,56392477.0,73532931,16106157.0,57149984

In [89]:
df[df['Health Insurance Coverage Change (2010-2015)']>10.1]

,State,Uninsured Rate (2010),Uninsured Rate (2015),Uninsured Rate Change (2010-2015),Health Insurance Coverage Change (2010-2015),Employer Health Insurance Coverage (2015),Marketplace Health Insurance Coverage (2016),Marketplace Tax Credits (2016),Average Monthly Tax Credit (2016),State Medicaid Expansion (2016),Medicaid Enrollment (2013),Medicaid Enrollment (2016),Medicaid Enrollment Change (2013-2016),Medicare Enrollment (2016)
0,Alabama,14.6%,10.1%,-4.5%,215000,2545000,165534,152206,$310,False,799176.0,910775,111599.0,989855
1,Alaska,19.9%,14.9%,-5%,36000,390000,17995,16205,$750,True,122334.0,166625,44291.0,88966
2,Arizona,16.9%,10.8%,-6.1%,410000,3288000,179445,124346,$230,True,1201770.0,1716198,514428.0,1175624
3,Arkansas,17.5%,9.5%,-8%,234000,1365000,63357,56843,$306,True,556851.0,920194,363343.0,606146
4,California,18.5%,8.6%,-9.9%,3826000,19552000,1415428,1239893,$309,True,7755381.0,11843081,4087700.0,5829777
5,Colorado,15.9%,8.1%,-7.8%,419000,2949000,108311,67062,$318,True,783420.0,1375264,591844.0,820234
6,Connecticut,9.1%,6%,-3.1%,110000,2148000,102917,80759,$357,True,NaN,761137,NaN,644136
7,Delaware,9.7%,5.9%,-3.8%,35000,564000,25379,21467,$330,True,223324.0,236702,13378.0,186835
8,District of Columbia,7.6%,3.8%,-3.8%,25000,388000,17666,1224,$183,True,235786.0,255491,19705.0,90492
9,Florida,21.3%,13.3%,-8%,1597000,8847000,1531714,1428712,$305,False,3104996.0,3644673,539677.0,4149593
10,Georgia,19.7%,13.9%,-5.8%,581000,5240000,478016,427353,$291,False,1535090.0,1782301,247211.0,1574058
11,Hawaii,7.9%,4%,-3.9%,54000,867000,13313,10958,$270,True,288357.0,341200,52843.0,252514
12,Idaho,17.7%,11%,-6.7%,109000,836000,94270,82802,$265,False,238150.0,293905,55755.0,294284
13,Illinois,13.8%,7.1%,-6.7%,850000,7359000,335243,259701,$237,True,2626943.0,3117939,490996.0,2118300
14,Indiana,14.8%,9.6%,-5.2%,339000,3825000,168884,139437,$259,True,1120674.0,1489805,369131.0,1181014
15,Iowa,9.3%,5%,-4.3%,132000,1862000,48949,42595,$307,True,493515.0,619055,125540.0,587780
16,Kansas,13.9%,9.1%,-4.8%,137000,1659000,89566,75815,$247,False,378160.0,421638,43478.0,499753
17,Kentucky,15.3%,6%,-9.3%,404000,2316000,74640,56488,$258,True,606805.0,1220788,613983.0,881938
18,Louisiana,17.8%,11.9%,-5.9%,269000,2295000,184403,170806,$362,True,1019787.0,1328708,308921.0,817272
19,Maine,10.1%,8.4%,-1.7%,22000,702000,75240,63896,$342,False,NaN,273160,NaN,315160
20,Maryland,11.3%,6.6%,-4.7%,278000,3700000,135208,100844,$243,True,856297.0,1252304,396007.0,960848
21,Massachusetts,4.4%,2.8%,-1.6%,107000,4232000,207121,157751,$190,True,1296359.0,1684328,387969.0,1252277
22,Michigan,12.4%,6.1%,-6.3%,618000,5876000,313123,275080,$233,True,1912009.0,2300958,388949.0,1947787
23,Minnesota,9.1%,4.5%,-4.6%,250000,3319000,74060,47266,$203,True,873040.0,1051509,178469.0,944222
24,Mississippi,18.2%,12.7%,-5.5%,161000,1326000,77747,73246,$306,False,637229.0,693869,56640.0,571699
25,Missouri,13.2%,9.8%,-3.4%,203000,3389000,252044,225878,$315,False,846084.0,967284,121200.0,1163543
26,Montana,17.3%,11.6%,-5.7%,58000,510000,51758,44091,$306,True,148974.0,224048,75074.0,209389
27,Nebraska,11.5%,8.2%,-3.3%,62000,1100000,80213,72091,$296,False,244600.0,242702,-1898.0,322796
28,Nevada,22.6%,12.3%,-10.3%,294000,1505000,79876,71472,$268,True,332560.0,614298,281738.0,471747
29,New Hampshire,11.1%,6.3%,-4.8%,63000,853000,49114,31151,$261,True,127082.0,189429,62347.0,275803
30,New Jersey,13.2%,8.7%,-4.5%,398000,5450000,249395,205242,$322,True,1283851.0,1784529,500678.0,1528961
31,New Mexico,19.6%,10.9%,-8.7%,178000,884000,47497,32703,$212,True,457678.0,766732,309054.0,385918
32,New York,11.9%,7.1%,-4.8%,939000,10895000,224014,123830,$178,True,5678417.0,6431165,752748.0,3424666
33,North Carolina,16.8%,11.2%,-5.6%,552000,4934000,545354,499178,$401,False,1595952.0,2072282,476330.0,1823454
34,North Dakota,9.8%,7.8%,-2%,15000,450000,20536,17630,$262,True,69980.0,89763,19783.0,122294
35,Ohio,12.3%,6.5%,-5.8%,664000,6831000,212046,174448,$250,True,2341481.0,3003170,661689.0,2208504
36,Oklahoma,18.9%,13.9%,-5%,192000,1948000,130178,113209,$298,False,790051.0,788544,-1507.0,693677
37,Oregon,17.1%,7%,-10.1%,403000,2070000,131167,95507,$253,True,626356.0,1021862,395506.0,784032
38,Pennsylvania,10.2%,6.4%,-3.8%,479000,7502000,412347,321345,$248,True,2386046.0,2883114,497068.0,2588577
39,Rhode Island,12.2%,5.7%,-6.5%,68000,597000,35583,30015,$250,True,190833.0,287173,96340.0,208324
40,South Carolina,17.5%,10.9%,-6.6%,317000,2487000,204846,186345,$312,False,889744.0,994804,105060.0,974114
41,South Dakota,12.4%,10.2%,-2.2%,19000,449000,24578,22005,$307,False,115501.0,119835,4334.0,161464
42,Tennessee,14.4%,10.3%,-4.1%,266000,3369000,231705,203112,$299,False,1244516.0,1627100,382584.0,1266920
43,Texas,23.7%,17.1%,-6.6%,1781000,13709000,1092650,913177,$271,False,4441605.0,4770229,328624.0,3765946
44,Utah,15.3%,10.5%,-4.8%,143000,1897000,164415,145288,$187,False,294029.0,314182,20153.0,358887
45,Vermont,8%,3.8%,-4.2%,26000,345000,27883,19575,$300,True,161081.0,175597,14516.0,136021
46,Virginia,13.1%,9.1%,-4%,327000,4850000,378838,319068,$276,False,935434.0,988821,53387.0,1392261
47,Washington,14.2%,6.6%,-7.6%,537000,3986000,158245,110476,$238,True,1117576.0,1788536,670960.0,1238649
48,West Virginia,14.6%,6%,-8.6%,156000,976000,33235,29163,$388,True,354544.0,575645,221101.0,423500
49,Wisconsin,9.4%,5.7%,-3.7%,211000,3521000,224208,190542,$332,False,985531.0,1046897,61366.0,1084854
50,Wyoming,14.9%,11.5%,-3.4%,20000,335000,22076,20313,$459,False,67518.0,63583,-3935.0,99128
51,United States,15.5%,9.4%,6.1%,19304000,172292000,11081330,9389609,$291,NaN,56392477.0,73532931,16106157.0,57149984